//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.FDTransactions = new HashSet<FDTransaction>();
            this.LoanTransactions = new HashSet<LoanTransaction>();
        }
    
        public int EmpAuto { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string Gender { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string PAN { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public string DeptID { get; set; }
        public string EmpType { get; set; }
        public string ManagerID { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDTransaction> FDTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanTransaction> LoanTransactions { get; set; }
    }
}
