//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public int TransactionID { get; set; }
        public string LoanAccountID { get; set; }
        public System.DateTime EMIDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public string ProcessedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LoanAccount LoanAccount { get; set; }
    }
}
