//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SavingsAccount()
        {
            this.SavingsTransactions = new HashSet<SavingsTransaction>();
        }
    
        public int SBAuto { get; set; }
        public string SBAccountID { get; set; }
        public string CustID { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavingsTransaction> SavingsTransactions { get; set; }
    }
}
